apiVersion: v1
kind: Service
metadata:
  name: checkoutservice
  namespace: apps
  labels:
    app: checkoutservice
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8082"
    prometheus.io/path: "/metrics"

spec:
  type: ClusterIP
  selector:
    app: checkoutservice
  ports:
    - name: grpc
      port: 5050
      targetPort: 5050
    - name: http
      port: 8082
      targetPort: 8082
