deployment:
  replicas: 2
service:
  type: LoadBalancer
providers:
  kubernetesIngress:
    publishedService:
      enabled: true
logs:
  general:
    level: INFO
  access:
    enabled: true
ports:
  web:
    redirectTo:
      port: websecure
  websecure:
    tls:
      enabled: true
