apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
      labels:
        app: paymentservice
    spec:
      terminationGracePeriodSeconds: 5
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: paymentservice
          image: magdyeldeeb/microservices-k8s:paymentservice-1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50051
            - containerPort: 8080
          env:
            - name: PORT
              value: "50051"
            - name: DISABLE_PROFILER
              value: "1"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          readinessProbe:
            grpc:
              port: 50051
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
          livenessProbe:
            grpc:
              port: 50051
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
