apiVersion: v1
kind: Service
metadata:
  name: emailservice
  namespace: apps
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8081"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: emailservice
  type: ClusterIP
  ports:
    - name: grpc
      port: 5000
      targetPort: 5000
    - name: http
      port: 8081
      targetPort: 8081
